// TỆP TẠO TỰ ĐỘNG từ i18n/labels.json bằng "npm run build". Không sửa tay.
// Mỗi khóa: [Việt, 中文, màu?] (phụ lục 1.5 mục 5.3)
export const DICT = {"nav.home":["Trang chủ","首页"],
"nav.work":["Công việc","工单"],
"nav.scan":["Quét QR","扫码"],
"nav.alerts":["Nhắc hạn","到期提醒"],
"nav.account":["Tài khoản","账户"],
"menu.title":["Danh mục","功能菜单"],
"module.equipment":["Thiết bị","设备"],
"module.maintenance":["Bảo trì","保养"],
"module.repairs":["Sửa chữa","维修"],
"module.warehouse":["Kho vật tư","物料库"],
"module.utilities":["Điện nước","水电"],
"module.reports":["Báo cáo","报表"],
"module.circuits":["Tra cứu lộ điện","电路查询"],
"module.contracts":["Hợp đồng thuê ngoài","外包合同"],
"module.inspections":["Kiểm định","检验"],
"tab.specs":["Thông số","参数"],
"tab.parts":["Linh kiện","配件"],
"tab.documents":["Tài liệu","文件"],
"tab.history":["Lịch sử","历史记录"],
"tab.plans":["Kế hoạch","计划"],
"tab.work_orders":["Phiếu thực hiện","执行工单"],
"tab.calendar":["Lịch","日程"],
"tab.catalog":["Danh mục","物料目录"],
"tab.parts_by_equipment":["Vật tư theo máy","设备用料"],
"tab.requests":["Đề nghị","物料申请"],
"tab.usage":["Lượng dùng","物料用量"],
"btn.import_excel":["Nhập Excel","导入Excel"],
"btn.export_excel":["Xuất Excel","导出Excel"],
"btn.report":["Báo cáo","报表"],
"btn.qr":["QR","二维码"],
"btn.view_qr":["Xem QR","查看二维码"],
"btn.print_qr":["In QR","打印二维码"],
"btn.save_draft":["Lưu nháp","保存草稿"],
"btn.submit_review":["Gửi duyệt","提交审核"],
"btn.submit_acceptance":["Gửi nghiệm thu","提交验收"],
"btn.approve":["Duyệt","批准"],
"btn.reject":["Từ chối","驳回"],
"btn.accept_pass":["Nghiệm thu đạt","验收通过"],
"btn.accept_fail":["Không đạt, trả lại","验收不通过"],
"btn.add":["Thêm","新增"],
"btn.edit":["Sửa","编辑"],
"btn.save":["Lưu","保存"],
"btn.cancel":["Hủy","取消"],
"btn.back":["Quay lại","返回"],
"btn.close":["Đóng","关闭"],
"btn.ok":["Đồng ý","确定"],
"btn.confirm":["Đúng","确认"],
"btn.retry":["Thử lại","重试"],
"btn.more":["Thêm thao tác","更多操作"],
"btn.search":["Tìm","搜索"],
"btn.filter":["Lọc","筛选"],
"btn.clear_filter":["Bỏ lọc","清除筛选"],
"btn.sync_now":["Đồng bộ ngay","立即同步"],
"btn.export_backup":["Xuất dự phòng","导出备份"],
"btn.keep_drafts":["Giữ nháp trên máy","保留本机草稿"],
"btn.delete_drafts":["Xóa nháp","删除草稿"],
"btn.delete_draft":["Xóa nháp","删除草稿"],
"btn.change_pin":["Đổi PIN","修改PIN"],
"btn.logout":["Đăng xuất","退出登录"],
"btn.logout_all":["Đăng xuất mọi thiết bị","退出所有设备"],
"btn.relogin":["Đăng nhập lại","重新登录"],
"btn.download":["Tải về","下载"],
"btn.open_save":["Mở / Lưu","打开/保存"],
"btn.download_offline":["Tải để xem ngoại tuyến","下载以离线查看"],
"btn.set_private":["Đặt riêng tư","设为私有"],
"btn.suggest_translation":["Gợi ý dịch","翻译建议"],
"btn.retranslate":["Dịch lại","重新翻译"],
"btn.backup_now":["Sao lưu ngay","立即备份"],
"btn.resend":["Gửi lại","重新发送"],
"btn.archive":["Ngừng sử dụng","停用"],
"btn.unarchive":["Dùng lại","恢复使用"],
"btn.upload":["Tải lên","上传"],
"btn.add_link":["Thêm liên kết","添加链接"],
"btn.take_photo":["Chụp ảnh","拍照"],
"btn.choose_file":["Chọn tệp","选择文件"],
"btn.remove":["Bỏ","移除"],
"btn.use_server":["Dùng bản máy chủ","采用服务器版本"],
"btn.edit_on_server":["Sửa tiếp trên bản máy chủ","基于服务器版本修改"],
"btn.copy_to_draft":["Chép thành nháp mới","复制为新草稿"],
"btn.view":["Xem","查看"],
"btn.open":["Mở","打开"],
"btn.revoke":["Thu hồi","撤销"],
"btn.replace_part":["Thay linh kiện","更换配件"],
"btn.link_part":["Gắn linh kiện có sẵn","关联已有配件"],
"btn.new_part":["Thêm linh kiện mới","新增配件"],
"btn.edit_unlink":["Sửa/Gỡ liên kết","编辑或解除关联"],
"btn.unlink":["Gỡ liên kết","解除关联"],
"btn.schedule":["Lịch hẹn","预约"],
"btn.month_calendar":["Lịch tháng","月历"],
"btn.acknowledge":["Tiếp nhận","受理"],
"wo_status.DRAFT":["Nháp","草稿","grey"],
"wo_status.ASSIGNED":["Đã giao việc","已分配","navy"],
"wo_status.IN_PROGRESS":["Đang làm","进行中","navy"],
"wo_status.PENDING_ACCEPTANCE":["Chờ nghiệm thu","待验收","amber"],
"wo_status.COMPLETED":["Hoàn thành","已完成","green"],
"wo_status.CANCELLED":["Đã hủy","已取消","grey"],
"repair_status.REPORTED":["Mới báo","新报告","amber"],
"repair_status.ASSIGNED":["Đã phân công","已分配","navy"],
"repair_status.IN_PROGRESS":["Đang xử lý","处理中","navy"],
"repair_status.PENDING_ACCEPTANCE":["Chờ nghiệm thu","待验收","amber"],
"repair_status.COMPLETED":["Hoàn thành","已完成","green"],
"repair_status.CANCELLED":["Đã hủy","已取消","grey"],
"mreq_status.DRAFT":["Nháp","草稿","grey"],
"mreq_status.PENDING_APPROVAL":["Chờ duyệt","待审核","amber"],
"mreq_status.APPROVED":["Đã duyệt","已批准","green"],
"mreq_status.REJECTED":["Bị từ chối","已驳回","red"],
"mreq_status.CANCELLED":["Đã hủy","已取消","grey"],
"mreq_status.PENDING_WAREHOUSE":["Chờ chuyển kho","待转仓库","amber"],
"mreq_status.SENT":["Đã gửi kho","已发送仓库","navy"],
"mreq_status.PARTIALLY_ISSUED":["Đã xuất một phần","部分出库","amber"],
"mreq_status.FULFILLED":["Đã xuất đủ","已全部出库","green"],
"cert_status.DRAFT":["Nháp","草稿","grey"],
"cert_status.PENDING_APPROVAL":["Chờ duyệt","待审核","amber"],
"cert_status.APPROVED":["Đã duyệt","已批准","green"],
"cert_status.REJECTED":["Bị từ chối","已驳回","red"],
"cert_status.SUPERSEDED":["Đã thay thế","已被取代","grey"],
"cert_status.REVOKED":["Đã thu hồi","已撤销","red"],
"renewal_status.DRAFT":["Nháp","草稿","grey"],
"renewal_status.PENDING_APPROVAL":["Chờ duyệt","待审核","amber"],
"renewal_status.APPROVED":["Đã duyệt","已批准","green"],
"renewal_status.REJECTED":["Bị từ chối","已驳回","red"],
"stock_status.DRAFT":["Nháp","草稿","grey"],
"stock_status.PENDING_APPROVAL":["Chờ duyệt","待审核","amber"],
"stock_status.APPROVED":["Đã duyệt","已批准","green"],
"stock_status.CANCELLED":["Đã hủy","已取消","grey"],
"stock_status.POSTED":["Đã chốt","已过账","green"],
"usage_status.DRAFT":["Nháp","草稿","grey"],
"usage_status.PENDING_CONFIRMATION":["Chờ xác nhận","待确认","amber"],
"usage_status.CONFIRMED":["Đã xác nhận","已确认","green"],
"reset_status.PREVIEWED":["Đã xem trước","已预览","grey"],
"reset_status.LOCKED":["Đã khóa vận hành","已锁定","amber"],
"reset_status.BACKING_UP":["Đang sao lưu","正在备份","navy"],
"reset_status.RESETTING":["Đang xóa","正在清除","navy"],
"reset_status.VERIFYING":["Đang kiểm tra","正在校验","navy"],
"reset_status.COMPLETED":["Hoàn tất","已完成","green"],
"reset_status.FAILED_NEEDS_RECOVERY":["Lỗi, cần xử lý tiếp","失败，需恢复","red"],
"import_status.VALIDATING":["Đang kiểm tra","校验中","navy"],
"import_status.NEEDS_FIX":["Cần sửa lỗi","需修正","red"],
"import_status.READY":["Sẵn sàng nhập","可导入","green"],
"import_status.PENDING_APPROVAL":["Chờ duyệt","待审核","amber"],
"import_status.COMMITTING":["Đang ghi","写入中","navy"],
"import_status.COMMITTED":["Đã nhập","已导入","green"],
"import_status.PARTIAL":["Nhập dở","部分导入","amber"],
"import_status.FAILED":["Thất bại","失败","red"],
"op_state.QUEUED":["Chờ gửi","待同步","amber"],
"op_state.PREPARED":["Đang gửi","同步中","navy"],
"op_state.SENDING":["Đang gửi","同步中","navy"],
"op_state.COMMITTED":["Đã lưu máy chủ","已同步","green"],
"op_state.FAILED":["Lỗi gửi","同步失败","red"],
"op_state.REJECTED":["Bị từ chối","被拒","red"],
"op_state.CONFLICT":["Xung đột","冲突","red"],
"op_state.UNKNOWN":["Chưa rõ kết quả","结果未知","amber"],
"op_state.UNKNOWN_RESULT":["Chưa rõ kết quả","结果未知","amber"],
"email_status.QUEUED":["Chờ gửi","待发送","amber"],
"email_status.SENDING":["Đang gửi","发送中","navy"],
"email_status.SENT":["Đã gửi","已发送","green"],
"email_status.FAILED":["Gửi lỗi","发送失败","red"],
"email_status.UNKNOWN":["Chưa rõ kết quả","结果未知","amber"],
"email_status.SKIPPED":["Bỏ qua","已跳过","grey"],
"contract_lifecycle.ACTIVE":["Đang hiệu lực","生效中","green"],
"contract_lifecycle.SUPERSEDED":["Đã thay thế","已被取代","grey"],
"contract_lifecycle.ENDED":["Đã kết thúc","已终止","grey"],
"contract_lifecycle.NOT_RENEWED":["Không gia hạn","不续约","grey"],
"alert_state.OPEN":["Đang nhắc","提醒中","amber"],
"alert_state.ACKNOWLEDGED":["Đã tiếp nhận","已受理","navy"],
"alert_state.RESOLVED":["Đã đóng","已关闭","grey"],
"user_status.ACTIVE":["Đang hoạt động","正常","green"],
"user_status.LOCKED":["Tạm khóa","已锁定","red"],
"user_status.MUST_CHANGE_PIN":["Phải đổi PIN","需修改PIN","amber"],
"user_status.DISABLED":["Ngừng dùng","已停用","grey"],
"backup_status.VERIFIED":["Đã kiểm chứng","已校验","green"],
"backup_status.INCONSISTENT":["Không nhất quán","不一致","amber"],
"backup_status.FAILED":["Thất bại","失败","red"],
"doc_kind.PHOTO_EQUIPMENT":["Ảnh thiết bị","设备照片"],
"doc_kind.PHOTO_MATERIAL":["Ảnh vật tư","物料照片"],
"doc_kind.PHOTO_SITE":["Ảnh hiện trường","现场照片"],
"doc_kind.PHOTO_METER":["Ảnh đồng hồ","表计照片"],
"doc_kind.CERTIFICATE":["Chứng nhận, biên bản kiểm định","检验证书、报告"],
"doc_kind.DRAWING":["Bản vẽ, sơ đồ","图纸、图表"],
"doc_kind.MANUAL":["Hướng dẫn, datasheet","说明书、技术资料"],
"doc_kind.IMPORT_FILE":["File Excel đã nhập","已导入文件"],
"doc_kind.OTHER":["Khác","其他"],
"doc_kind.CONTRACT":["Hợp đồng, phụ lục","合同、附件"],
"doc_kind.INVOICE":["Hóa đơn, biên bản dịch vụ","发票、服务记录"],
"doc_kind.REPORT_FILE":["File báo cáo đã tạo","已生成报表"],
"doc_scope.LINK_VIEW":["Ai có link: xem","知道链接者可查看","grey"],
"doc_scope.MODULE_VIEW":["Riêng tư","私有","navy"],
"doc_scope.COST_VIEW":["Riêng tư, có giá","私有（含价格）","navy"],
"sharing.NOT_SHARED":["Chưa chia sẻ","未共享","grey"],
"sharing.LINK_SHARED":["Đã chia sẻ link","已共享链接","green"],
"sharing.PENDING":["Đang chia sẻ","共享中","amber"],
"sharing.FAILED":["Chia sẻ lỗi","共享失败","red"],
"sharing.REVOKED":["Đã đưa về riêng tư","已设为私有","grey"],
"due_state.NOT_DUE":["Còn hạn","未到期","green"],
"due_state.DUE_SOON":["Sắp tới hạn — Còn {N} ngày","即将到期 — 剩余 {N} 天","amber"],
"due_state.DUE_TODAY":["Đến hạn hôm nay","今日到期","red"],
"due_state.OVERDUE":["Quá hạn {N} ngày","已逾期 {N} 天","red"],
"due_state.MISSING":["Chưa đủ hồ sơ","资料不全","amber"],
"due_filter.ALL":["Tất cả","全部"],
"due_filter.DUE_SOON":["Sắp tới hạn","即将到期"],
"due_filter.DUE_TODAY":["Đến hạn hôm nay","今日到期"],
"due_filter.OVERDUE":["Quá hạn","已逾期"],
"due_filter.MISSING":["Chưa đủ hồ sơ","资料不全"],
"record_status.INCOMPLETE":["Chưa đủ hồ sơ","资料不全","amber"],
"record_status.VALID":["Hợp lệ","有效","green"],
"record_status.FAILED":["Không đạt","不合格","red"],
"record_status.REVOKED":["Đã thu hồi","已撤销","red"],
"record_status.SUSPENDED":["Tạm ngưng","暂停","grey"],
"inspection_result.PASS":["Đạt","合格","green"],
"inspection_result.FAIL":["Không đạt","不合格","red"],
"inspection_result.CONDITIONAL_PASS":["Đạt có điều kiện","有条件合格","amber"],
"equipment_status.RUNNING":["Đang hoạt động","运行中","green"],
"equipment_status.STOPPED":["Dừng máy","停机","red"],
"equipment_status.UNDER_REPAIR":["Đang sửa","维修中","amber"],
"equipment_status.UNDER_MAINTENANCE":["Đang bảo trì","保养中","amber"],
"equipment_status.STANDBY":["Dự phòng","备用","grey"],
"equipment_status.RETIRED":["Ngừng sử dụng","停用","grey"],
"criticality.HIGH":["Quan trọng cao","关键"],
"criticality.MEDIUM":["Quan trọng","重要"],
"criticality.LOW":["Thường","一般"],
"severity.HIGH":["Cao","高","red"],
"severity.MEDIUM":["Trung bình","中","amber"],
"severity.LOW":["Thấp","低","grey"],
"priority.URGENT":["Khẩn","紧急","red"],
"priority.HIGH":["Cao","高","amber"],
"priority.NORMAL":["Thường","普通","grey"],
"priority.LOW":["Thấp","低","grey"],
"check_result.PENDING":["Chưa có kết quả","未填写","grey"],
"check_result.PASS":["Đạt","合格","green"],
"check_result.FAIL":["Không đạt","不合格","red"],
"check_result.NA":["Không áp dụng","不适用","grey"],
"overall_result.PASS":["Đạt","合格","green"],
"overall_result.FAIL":["Không đạt","不合格","red"],
"result_type.PASS_FAIL":["Đạt/Không đạt","合格/不合格"],
"result_type.NUMBER":["Số đo","测量值"],
"result_type.TEXT":["Ghi nhận","记录"],
"acceptance_result.PASS":["Nghiệm thu đạt","验收通过","green"],
"acceptance_result.FAIL":["Nghiệm thu không đạt","验收不通过","red"],
"material_group.EQUIPMENT_PART":["Linh kiện thiết bị","设备配件"],
"material_group.ELECTRICAL":["Vật tư điện","电气物料"],
"material_group.WATER":["Vật tư nước","给排水物料"],
"material_group.CONSUMABLE":["Vật tư tiêu hao","耗材"],
"material_group.TOOL":["Dụng cụ","工具"],
"material_group.PPE":["Bảo hộ","劳保用品"],
"item_kind.COMPONENT":["Linh kiện","配件"],
"item_kind.CONSUMABLE":["Tiêu hao","消耗品"],
"item_kind.REUSABLE_TOOL":["Dụng cụ dùng lại","可重复使用工具"],
"equipment_component.TRUE":["Gắn máy được","可关联设备","navy"],
"equipment_component.FALSE":["Không gắn máy","不关联设备","grey"],
"material_active.TRUE":["Đang dùng","在用","green"],
"material_active.FALSE":["Ngừng dùng","停用","grey"],
"utility_type.ELECTRICITY":["Điện","电"],
"utility_type.WATER":["Nước","水"],
"cost_source.MANUAL_REFERENCE":["Tham khảo","参考"],
"cost_source.WAREHOUSE_POSTED":["Kho đã chốt","仓库已过账"],
"part.unconfirmed":["Chưa xác nhận","未确认","amber"],
"part.confirmed":["Đã xác nhận","已确认","green"],
"part_event.LINKED":["Gắn linh kiện","关联配件"],
"part_event.EDITED":["Sửa liên kết","修改关联"],
"part_event.UNLINKED":["Gỡ liên kết","解除关联"],
"part_event.APPROVED":["Xác nhận liên kết","确认关联"],
"part_event.REMOVED":["Tháo","拆下"],
"part_event.INSTALLED":["Lắp","安装"],
"part_event.REPLACED":["Thay","更换"],
"sync.offline":["Ngoại tuyến","离线"],
"sync.online":["Trực tuyến","在线"],
"sync.local_saved":["Đã lưu trên máy","已保存在本机"],
"sync.queued":["Chờ gửi","待同步"],
"sync.queued_count":["{N} mục chờ gửi","待同步数据 {N} 条"],
"sync.sending":["Đang gửi","同步中"],
"sync.committed":["Đã lưu máy chủ","已同步"],
"sync.conflict":["Xung đột, cần xử lý","冲突，需处理"],
"sync.failed":["Lỗi gửi","同步失败"],
"sync.last":["Lần đồng bộ cuối","上次同步"],
"sync.offline_data":["Dữ liệu ngoại tuyến, cập nhật lúc {T}","离线数据，更新于 {T}"],
"sync.need_network":["Cần kết nối mạng","需要网络连接"],
"sync.dataset_reset":["Dữ liệu đã được đặt lại, cần tải lại","数据已重置，需重新加载"],
"sync.safari_tab":["Đang chạy trong Safari: nháp có thể bị xóa sau 7 ngày không mở","在Safari中运行：7天未打开草稿可能被清除"],
"sync.syncing":["Đang đồng bộ…","正在同步…"],
"sync.done":["Đã đồng bộ","同步完成"],
"sync.never":["Chưa đồng bộ","尚未同步"],
"draft.rejected":["Nháp bị từ chối","被拒草稿"],
"draft.old_epoch":["Nháp thế hệ dữ liệu cũ","旧数据草稿"],
"draft.other_user":["Máy còn {N} nháp của người dùng khác","本机有 {N} 份其他用户的草稿"],
"draft.title":["Nháp chờ đồng bộ","待同步草稿"],
"draft.empty":["Không có mục nào","没有项目"],
"draft.auto_delete":["Tự xóa sau {N} ngày","{N} 天后自动删除"],
"draft.delete_confirm":["Xóa hẳn nháp này? Không lấy lại được.","确定删除此草稿？删除后无法恢复。"],
"draft.delete_all_confirm":["Xóa hẳn {N} nháp chưa gửi? Không lấy lại được.","确定删除 {N} 份未同步草稿？删除后无法恢复。"],
"draft.photos":["{N} ảnh","{N} 张照片"],
"draft.created":["Tạo lúc","创建时间"],
"draft.error_code":["Mã lỗi","错误代码"],
"draft.size":["Dung lượng","大小"],
"action.inspection.submit":["Nộp chứng nhận kiểm định","提交检验证书"],
"action.contract.service.record":["Ghi dịch vụ hợp đồng","记录合同服务"],
"action.doc.upload":["Tải tài liệu lên","上传文件"],
"action.equipment.edit":["Sửa thiết bị","编辑设备"],
"action.material.edit":["Sửa vật tư","编辑物料"],
"conflict.title":["Xử lý xung đột","处理冲突"],
"conflict.mine":["Bản của tôi","我的版本"],
"conflict.server":["Bản máy chủ","服务器版本"],
"conflict.diff":["Khác nhau","不同"],
"conflict.by":["Người sửa","修改人"],
"conflict.at":["Lúc","时间"],
"conflict.use_server_confirm":["Bỏ thay đổi của bạn và dùng bản máy chủ? Có thể xuất dự phòng trước.","放弃您的修改并采用服务器版本？可先导出备份。"],
"conflict.help":["Có người đã sửa hồ sơ này trước bạn. Không có nút ghi đè: chọn dùng bản máy chủ hoặc sửa tiếp trên bản máy chủ.","此记录已被他人先行修改。不提供覆盖：请采用服务器版本，或基于服务器版本继续修改。"],
"auth.offline_unlock":["Mở khóa ngoại tuyến","离线解锁"],
"auth.failed":["Mã nhân viên hoặc PIN không đúng","工号或PIN错误"],
"auth.locked":["Tạm khóa do nhập sai PIN nhiều lần, thử lại sau {N} phút","因多次输错PIN已暂时锁定，请 {N} 分钟后重试"],
"auth.paused":["Đăng nhập đang tạm dừng, thử lại sau {N} phút","登录已暂停，请 {N} 分钟后重试"],
"auth.attempts_left":["Còn {N} lần thử","还可尝试 {N} 次"],
"auth.temp_pin":["Bạn đang dùng PIN tạm, hãy đặt PIN mới","您正在使用临时PIN，请设置新PIN"],
"auth.reauth":["Nhập lại PIN để tiếp tục","请重新输入PIN以继续"],
"auth.revoked":["Phiên đã bị thu hồi hoặc quyền đã thay đổi","会话已撤销或权限已变更"],
"auth.session_warn":["Phiên sắp hết hạn — {D}","会话即将到期 — {D}"],
"auth.shared_device":["Máy dùng chung","公用设备"],
"auth.switch_user":["Đăng nhập người khác","切换用户"],
"auth.open_with_pin":["Mở bằng PIN","用PIN打开"],
"auth.expired_offline":["Phiên đã hết hạn: chỉ xem nháp và xuất dự phòng","会话已过期：只能查看草稿和导出备份"],
"auth.server_slow":["Máy chủ đang phản hồi chậm…","服务器响应较慢…"],
"auth.need_online_login":["Cần đăng nhập trực tuyến","需在线登录"],
"auth.others_relogin":["Các thiết bị khác phải đăng nhập lại","其他设备需重新登录"],
"auth.logout_all_confirm":["Mọi phiên, kể cả máy đang dùng, sẽ hết hiệu lực. Dùng khi mất điện thoại.","所有会话（包括本机）将失效。用于手机丢失时。"],
"auth.logout_has_drafts":["Còn {N} mục chưa gửi lên máy chủ. Chọn cách xử lý trước khi đăng xuất.","仍有 {N} 条未同步到服务器。退出前请选择处理方式。"],
"level.1":["Tra cứu","查询"],
"level.2":["Nhân viên","员工"],
"level.3":["Trưởng bộ phận","部门主管"],
"level.4":["Quản trị","管理员"],
"level.owner":["Chủ hệ thống","系统所有者"],
"subrole.KY_THUAT":["Kỹ thuật viên","技术员"],
"subrole.DOC_DIEN_NUOC":["Đọc điện nước","抄表员"],
"subrole.HD_KD":["Quản lý hợp đồng/kiểm định","合同/检验管理"],
"subrole.THU_KHO":["Thủ kho","仓管员"],
"subrole.BAO_SU_CO":["Báo sự cố","报修员"],
"account.profile":["Hồ sơ","个人资料"],
"account.display_name":["Tên hiển thị","显示名称"],
"account.level":["Cấp","级别"],
"account.subroles":["Vai trò","岗位"],
"account.no_subrole":["Chưa được giao vai trò","未分配岗位"],
"account.sync":["Đồng bộ","同步"],
"account.security":["Bảo mật","安全"],
"account.sessions":["Phiên đăng nhập","登录会话"],
"account.this_device":["Máy này","本机"],
"account.issued":["Đăng nhập lúc","登录时间"],
"account.last_seen":["Hoạt động gần nhất","最近活动"],
"account.expires":["Hết hạn","到期"],
"account.guide":["Hướng dẫn","使用指南"],
"account.add_home":["Thêm app vào Màn hình chính: trong Safari bấm Chia sẻ → Thêm vào MH chính","将应用添加到主屏幕：在Safari中点击分享→添加到主屏幕"],
"account.info":["Thông tin","信息"],
"account.app_version":["Phiên bản app","应用版本"],
"account.api_version":["Phiên bản API","API版本"],
"account.server_version":["Phiên bản máy chủ","服务器版本"],
"account.admin":["Quản trị","管理"],
"account.poc":["Bàn thử PoC","PoC测试台"],
"admin.users":["Người dùng và PIN tạm","用户与临时PIN"],
"admin.permissions":["Phân quyền","权限"],
"admin.catalog":["Danh mục chung","基础数据"],
"admin.gmail":["Người nhận Gmail và nhật ký gửi","邮件收件人与发送记录"],
"admin.backup":["Sao lưu","备份"],
"admin.audit":["Nhật ký thao tác","操作日志"],
"admin.status":["Trạng thái hệ thống","系统状态"],
"admin.system_data":["Dữ liệu hệ thống","系统数据"],
"home.week":["Lịch tuần này","本周日程"],
"home.deadlines":["Thời hạn quan trọng","重要期限"],
"home.due_soon":["Sắp tới hạn","即将到期"],
"home.overdue":["Quá hạn","已逾期"],
"home.none":["Không có","无"],
"home.today_work":["Công việc hôm nay","今日工作"],
"home.no_work_today":["Không có việc hôm nay","今天没有任务"],
"home.wo_coming":["Phiếu bảo trì/sửa chữa","保养/维修工单"],
"home.item_inspection":["Kiểm định","检验"],
"home.item_contract":["Hợp đồng","合同"],
"home.item_service":["Dịch vụ HĐ","合同服务"],
"home.records":["{N} hồ sơ","{N} 条"],
"col.type":["Loại","类型"],
"col.code":["Mã","编号"],
"col.content":["Nội dung","内容"],
"col.equipment_location":["Thiết bị/Khu vực","设备/区域"],
"col.due":["Hạn","期限"],
"col.status":["Trạng thái","状态"],
"col.owner":["Phụ trách","负责人"],
"col.name":["Tên","名称"],
"col.actions":["Thao tác","操作"],
"weekday.1":["T2","周一"],
"weekday.2":["T3","周二"],
"weekday.3":["T4","周三"],
"weekday.4":["T5","周四"],
"weekday.5":["T6","周五"],
"weekday.6":["T7","周六"],
"weekday.7":["CN","周日"],
"screen.equipment_list":["Thiết bị","设备"],
"screen.equipment":["Hồ sơ thiết bị","设备档案"],
"screen.equipment_new":["Thêm thiết bị","新增设备"],
"screen.equipment_edit":["Sửa thiết bị","编辑设备"],
"screen.material":["Hồ sơ vật tư","物料档案"],
"screen.material_new":["Thêm vật tư","新增物料"],
"screen.material_edit":["Sửa vật tư","编辑物料"],
"screen.spec_edit":["Thông số","参数"],
"screen.part_link":["Gắn linh kiện","关联配件"],
"screen.qr":["Mã QR","二维码"],
"screen.labels":["In tem QR","打印二维码标签"],
"field.valid_from":["Hiệu lực từ","有效期自"],
"field.valid_to":["Hiệu lực đến","有效期至"],
"field.end_date":["Ngày hết hạn","到期日"],
"field.renewal_notice_date":["Hạn báo gia hạn","续约通知期限"],
"field.not_set":["Chưa có","暂无"],
"field.equipment_code":["Mã thiết bị","设备编号"],
"field.code_auto":["Để trống để máy chủ tự cấp mã","留空则由服务器自动编号"],
"field.name":["Tên","名称"],
"field.name_vi":["Tên tiếng Việt","越南语名称"],
"field.name_zh":["Tên tiếng Trung","中文名称"],
"field.one_lang":["Chỉ cần nhập một thứ tiếng, máy chủ tự dịch bên kia","只需填写一种语言，服务器自动翻译另一种"],
"field.category":["Loại thiết bị","设备类别"],
"field.location":["Khu vực","区域"],
"field.vendor":["Nhà cung cấp","供应商"],
"field.manufacturer":["Hãng sản xuất","制造商"],
"field.model":["Model","型号"],
"field.serial":["Số serial","序列号"],
"field.manufacture_year":["Năm sản xuất","制造年份"],
"field.install_date":["Ngày lắp đặt","安装日期"],
"field.warranty_end":["Hết bảo hành","保修到期"],
"field.status":["Tình trạng","状态"],
"field.criticality":["Mức quan trọng","重要程度"],
"field.owner":["Người phụ trách","负责人"],
"field.reason":["Lý do","原因"],
"field.reason_required":["Bắt buộc nhập lý do","必须填写原因"],
"field.choose":["— Chọn —","— 请选择 —"],
"field.none":["— Không —","— 无 —"],
"field.search_placeholder":["Tìm mã, tên, model, serial","搜索编号、名称、型号、序列号"],
"field.include_retired":["Gồm thiết bị ngừng sử dụng","含停用设备"],
"field.total":["Tổng {N}","共 {N} 条"],
"field.new_status":["Tình trạng khi dùng lại","恢复后的状态"],
"field.qr_key":["Mã tem","标签码"],
"field.document_title":["Tên tài liệu","文件名称"],
"field.document_kind":["Loại tài liệu","文件类型"],
"field.document_date":["Ngày tài liệu","文件日期"],
"field.file_version":["Phiên bản","版本"],
"field.external_url":["Liên kết","链接"],
"field.uploaded_by":["Người tải lên","上传人"],
"field.material_code":["Mã vật tư","物料编号"],
"field.part_number":["Part number","零件号"],
"field.specification":["Thông số","规格"],
"field.specification_vi":["Thông số tiếng Việt","越南语规格"],
"field.specification_zh":["Thông số tiếng Trung","中文规格"],
"field.base_unit":["Đơn vị cơ sở","基本单位"],
"field.lead_time_days":["Thời gian đặt hàng (ngày)","订货周期（天）"],
"field.group":["Nhóm","分组"],
"field.item_kind":["Loại","类型"],
"field.is_component":["Gắn máy được","可关联设备"],
"field.installed_qty":["Lượng lắp","安装数量"],
"field.unit":["Đơn vị","单位"],
"field.function":["Chức năng","功能"],
"field.function_vi":["Chức năng tiếng Việt","越南语功能"],
"field.function_zh":["Chức năng tiếng Trung","中文功能"],
"field.position":["Vị trí lắp","安装位置"],
"field.position_vi":["Vị trí lắp tiếng Việt","越南语安装位置"],
"field.position_zh":["Vị trí lắp tiếng Trung","中文安装位置"],
"field.alternate":["Thay thế được duyệt","已批准替代件"],
"field.compatibility_note":["Ghi chú tương thích","兼容性说明"],
"field.effective_from":["Từ ngày","生效日期"],
"field.material":["Vật tư","物料"],
"field.spec_key":["Thông số","参数"],
"field.spec_value":["Giá trị","数值"],
"field.spec_text":["Giá trị dạng chữ","文字值"],
"field.sort_order":["Thứ tự","排序"],
"field.used_on":["Dùng cho thiết bị","适用设备"],
"field.stock":["Tồn kho","库存"],
"field.usage_history":["Lịch sử dùng","使用记录"],
"field.photos":["Ảnh","照片"],
"field.event":["Sự kiện","事件"],
"field.date":["Ngày","日期"],
"field.actor":["Người làm","执行人"],
"field.note":["Ghi chú","备注"],
"field.inspection_type":["Loại kiểm định","检验类型"],
"field.certificate_number":["Số chứng nhận","证书编号"],
"field.inspection_date":["Ngày kiểm định","检验日期"],
"field.result":["Kết quả","结果"],
"field.contract":["Hợp đồng","合同"],
"field.service":["Dịch vụ","服务"],
"field.required":["Bắt buộc nhập","必填"],
"field.invalid":["Giá trị không hợp lệ","值无效"],
"field.invalid_date":["Ngày không hợp lệ","日期无效"],
"field.year_invalid":["Năm phải từ 1900 đến 2100","年份须在1900至2100之间"],
"field.selected":["Đã chọn {N}","已选 {N} 项"],
"field.custom_spec":["Thông số khác (danh mục)","其他参数（目录）"],
"field.no_records":["Không có hồ sơ phù hợp","没有符合条件的记录"],
"field.loading":["Đang tải…","加载中…"],
"form.draft_restored":["Đã khôi phục nội dung chưa lưu trên máy","已恢复本机未保存的内容"],
"form.discard_draft":["Bỏ nội dung chưa lưu","放弃未保存内容"],
"form.saved":["Đã lưu máy chủ","已同步"],
"form.my_value":["Bản của tôi","我的版本"],
"form.server_loaded":["Đã nạp bản máy chủ. Chép lại thay đổi của bạn rồi Lưu","已载入服务器版本，请重新填写您的修改后保存"],
"field.number_ambiguous":["Đã hiểu là {A}. Nếu là số hàng nghìn, gõ liền không dấu (vd 12350)","已识别为 {A}；如为千位数，请连续输入（如 12350）"],
"field.number_bad_sep":["Không dùng dấu chấm/phẩy để tách hàng nghìn; gõ 1234567","请勿使用千位分隔符，请输入 1234567"],
"field.unit_not_allowed":["Đơn vị không thuộc danh sách cho phép","单位不在允许范围内"],
"spec.voltage":["Điện áp","电压"],
"spec.rated_current":["Dòng điện định mức","额定电流"],
"spec.electrical_power":["Công suất điện","电功率"],
"spec.frequency":["Tần số","频率"],
"spec.working_pressure":["Áp suất làm việc","工作压力"],
"spec.flow_rate":["Lưu lượng","流量"],
"spec.speed":["Tốc độ","转速"],
"spec.dimensions":["Kích thước (D × R × C)","外形尺寸（长×宽×高）"],
"spec.weight":["Trọng lượng","重量"],
"spec.throughput":["Năng suất","产能"],
"spec.rated_capacity_kva":["Dung lượng định mức (MBA)","额定容量"],
"lookup_group.EQUIPMENT_CATEGORY":["Loại thiết bị","设备类别"],
"lookup_group.UNIT":["Đơn vị tính","计量单位"],
"lookup_group.SPEC_KEY":["Mẫu thông số","参数模板"],
"lookup_group.CAUSE":["Nguyên nhân","原因"],
"eq.summary":["Thông tin chung","基本信息"],
"eq.archive_title":["Ngừng sử dụng thiết bị","停用设备"],
"eq.archive_help":["Thiết bị chuyển sang Ngừng sử dụng và ẩn khỏi danh sách; tem QR báo hồ sơ đã ngừng; ảnh đang chia sẻ link được đưa về riêng tư","设备将标为停用并从列表隐藏；二维码提示记录已停用；已共享链接的照片将设为私有"],
"eq.unarchive_title":["Dùng lại thiết bị","恢复使用设备"],
"eq.no_specs":["Chưa có thông số","暂无参数"],
"eq.add_spec":["Thêm thông số","新增参数"],
"eq.remove_spec_confirm":["Bỏ dòng thông số này?","移除此参数？"],
"eq.upload_photo":["Chụp/chọn ảnh thiết bị","拍摄/选择设备照片"],
"eq.upload_file":["Tải tệp lên (PDF, ảnh)","上传文件（PDF、图片）"],
"eq.archived_banner":["Thiết bị đã ngừng sử dụng","设备已停用"],
"doc.archive_confirm":["Gỡ tài liệu này khỏi hồ sơ? Tệp trên Drive không bị xóa.","从档案中移除此文件？Drive中的文件不会被删除。"],
"doc.set_private_confirm":["Đưa ảnh về riêng tư? Không có chiều ngược lại.","将照片设为私有？此操作不可撤销。"],
"doc.link_open":["Mở liên kết","打开链接"],
"doc.queued_offline":["Đã lưu trên máy, sẽ gửi khi có mạng","已保存在本机，联网后同步"],
"mat.list":["Kho vật tư","物料库"],
"mat.search_placeholder":["Tìm mã, tên, part number, model","搜索编号、名称、零件号、型号"],
"mat.include_inactive":["Gồm vật tư ngừng dùng","含停用物料"],
"mat.archive_title":["Ngừng dùng vật tư","停用物料"],
"mat.archive_help":["Vật tư chuyển sang Ngừng dùng; máy đang gắn vẫn giữ liên kết và lịch sử","物料标为停用；已关联设备保留关联和历史"],
"mat.reactivate":["Dùng lại vật tư","恢复使用物料"],
"mat.no_parts":["Chưa gắn linh kiện","暂无配件"],
"mat.pick":["Chọn vật tư gắn máy được","选择可关联设备的物料"],
"mat.unlink_title":["Gỡ liên kết linh kiện","解除配件关联"],
"mat.unlink_help":["Kết thúc liên kết với máy này; vật tư vẫn còn trong danh mục","结束与此设备的关联；物料仍保留在目录中"],
"mat.approve_title":["Xác nhận liên kết","确认关联"],
"mat.not_used":["Chưa dùng cho thiết bị nào","尚未用于任何设备"],
"mat.tab_hint":["Thêm danh mục hoặc gắn linh kiện không tự trừ tồn kho","新增目录或关联配件不会自动扣减库存"],
"in.list":["Kiểm định","检验"],
"in.requirement":["Hồ sơ yêu cầu kiểm định","检验要求档案"],
"in.new_requirement":["Thêm yêu cầu kiểm định","新增检验要求"],
"in.edit_requirement":["Sửa yêu cầu kiểm định","编辑检验要求"],
"in.types":["Loại kiểm định","检验类型"],
"in.type_new":["Thêm loại kiểm định","新增检验类型"],
"in.submit":["Nộp chứng nhận mới","提交新证书"],
"in.record":["Lần kiểm định","检验记录"],
"in.current":["Chứng nhận hiện hành","现行证书"],
"in.no_current":["Chưa có chứng nhận được duyệt","暂无已批准证书"],
"in.pending":["Chờ duyệt","待审核"],
"in.target":["Áp dụng cho","适用对象"],
"in.by_equipment":["Theo thiết bị","按设备"],
"in.by_location":["Theo khu vực","按区域"],
"in.obligation":["Nghĩa vụ","义务"],
"in.operational":["Vận hành","运行状态"],
"in.revoke":["Thu hồi chứng nhận","撤销证书"],
"in.suspend":["Tạm ngưng","暂停"],
"in.resume":["Bỏ tạm ngưng","取消暂停"],
"in.revoke_help":["Chứng nhận hiện hành chuyển sang Đã thu hồi; hạn hiện hành giữ nguyên","现行证书将标为已撤销；现行期限保持不变"],
"in.approve_help":["Duyệt lần Đạt cập nhật hạn hiện hành; lần Không đạt giữ hạn cũ","批准合格记录将更新现行期限；不合格记录保留原期限"],
"in.reject_reason":["Lý do từ chối","驳回原因"],
"in.reference_basis":["Căn cứ","依据"],
"in.interval":["Chu kỳ tham khảo (tháng)","参考周期（月）"],
"in.required_docs":["Hồ sơ cần có","所需资料"],
"in.no_mt":["Nội dung pháp lý: không dịch tự động, nhập thủ công thứ tiếng còn lại","法规内容：不自动翻译，请手动填写另一种语言"],
"in.cert_photos":["Ảnh/tệp chứng nhận (riêng tư)","证书照片/文件（私有）"],
"in.equipment_photo":["Ảnh thiết bị (xem bằng link)","设备照片（链接查看）"],
"in.attachments":["Tệp đính kèm","附件"],
"in.restriction":["Hạn chế","限制条件"],
"in.cost":["Chi phí","费用"],
"in.next_due":["Hạn tiếp theo (nếu có)","下次期限（如有）"],
"in.month":["Tháng","月份"],
"in.no_requirements":["Chưa có yêu cầu kiểm định","暂无检验要求"],
"obligation.REQUIRED":["Bắt buộc","强制"],
"obligation.VOLUNTARY":["Tự nguyện","自愿"],
"operational.ACTIVE":["Đang áp dụng","执行中","green"],
"operational.SUSPENDED":["Tạm ngưng","暂停","grey"],
"due_filter.NOT_DUE":["Còn hạn","未到期"],
"co.list":["Hợp đồng thuê ngoài","外包合同"],
"co.detail":["Hồ sơ hợp đồng","合同档案"],
"co.new":["Thêm hợp đồng","新增合同"],
"co.edit":["Sửa hợp đồng","编辑合同"],
"co.edit_terms":["Sửa hạn/giá trị","修改期限/金额"],
"co.edit_terms_help":["Chỉ để chữa sai nhập liệu của phiên hiện hành; bắt nhập lý do, cần PIN","仅用于更正现行版本的录入错误；须填写原因并输入PIN"],
"co.renewal":["Gia hạn","续约"],
"co.renewal_new":["Tạo dự thảo gia hạn","创建续约草稿"],
"co.renewal_draft":["Dự thảo gia hạn","续约草稿"],
"co.renewal_help":["Dự thảo không đổi hạn hiện hành; chỉ sau khi duyệt mới thành phiên hiện hành","草稿不改变现行期限；批准后才成为现行版本"],
"co.close":["Kết thúc hợp đồng","终止合同"],
"co.close_help":["Dừng nhắc hạn và không gửi Gmail cho hợp đồng này","停止该合同的到期提醒和邮件"],
"co.archive":["Lưu trữ hợp đồng","归档合同"],
"co.number":["Số hợp đồng","合同编号"],
"co.title":["Dịch vụ bảo dưỡng","保养服务"],
"co.start_date":["Ngày bắt đầu","开始日期"],
"co.value":["Giá trị","金额"],
"co.currency":["Tiền tệ","币种"],
"co.scope":["Phạm vi","范围"],
"co.revision":["Phiên","版本"],
"co.equipment":["Thiết bị trong phạm vi","合同范围内设备"],
"co.services":["Dịch vụ","服务"],
"co.add_equipment":["Thêm thiết bị","添加设备"],
"co.interval":["Chu kỳ","周期"],
"co.next_service":["Ngày dịch vụ tới","下次服务日期"],
"co.service_due":["Ngày dịch vụ","服务日期"],
"co.performed_at":["Ngày làm","执行日期"],
"co.result":["Kết quả","结果"],
"co.vendor_contact":["Người liên hệ bên cung cấp","供应商联系人"],
"co.record_service":["Ghi dịch vụ","记录服务"],
"co.accept_service":["Nghiệm thu dịch vụ","验收服务"],
"co.add_service":["Thêm lịch dịch vụ","新增服务计划"],
"co.days_left":["Còn lại","剩余"],
"co.history":["Các phiên","历次版本"],
"co.reference_marker":["đang nhắc","本次提醒"],
"co.no_contracts":["Chưa có hợp đồng","暂无合同"],
"co.lifecycle_filter":["Hiệu lực","效力"],
"co.close_kind":["Hình thức","方式"],
"service_status.PLANNED":["Chờ thực hiện","待执行","amber"],
"service_status.DONE":["Đã làm, chờ nghiệm thu","已执行，待验收","navy"],
"service_status.ACCEPTED":["Đã nghiệm thu","已验收","green"],
"interval.DAY":["ngày","天"],
"interval.WEEK":["tuần","周"],
"interval.MONTH":["tháng","月"],
"interval.YEAR":["năm","年"],
"history.part_events":["Linh kiện","配件"],
"history.contracts":["Hợp đồng","合同"],
"history.inspections":["Kiểm định","检验"],
"history.created":["Tạo hồ sơ","创建档案"],
"history.empty":["Chưa có lịch sử","暂无历史记录"],
"tag.machine_translated":["dịch máy","机器翻译"],
"tag.no_translation":["Chưa có bản dịch","暂无译文"],
"tag.warehouse_not_connected":["Chưa kết nối kho","尚未连接仓库"],
"tag.coming_soon":["Sắp có","即将推出"],
"tag.coming_soon_hint":["Chức năng sẽ có ở đợt sau","该功能将在后续版本推出"],
"tag.pending_code":["Chờ cấp mã","待分配编号"],
"tag.sample_data":["Dữ liệu mẫu","示例数据"],
"tag.env_test":["THỬ","测试"],
"tag.archived":["Đã lưu trữ","已归档","grey"],
"feature.not_enabled":["Chức năng chưa bật","功能尚未启用"],
"sys.maintenance":["Hệ thống đang bảo trì","系统维护中"],
"cost.hidden":["Không có quyền xem giá","无权查看价格"],
"qr.foreign":["Mã này không thuộc M&E","此码不属于M&E"],
"qr.unavailable":["Không tìm thấy hoặc không có quyền xem","未找到或无权查看"],
"qr.inactive":["Hồ sơ đã ngừng sử dụng","记录已停用"],
"qr.expired":["Tem đã hết hiệu lực","标签已失效"],
"qr.not_in_restored":["Không có mã này trong dữ liệu hiện tại; dữ liệu đã khôi phục về bản sao lưu cũ, tem in sau thời điểm đó cần in lại","当前数据中无此码；数据已恢复至旧备份，此后打印的标签需重新打印"],
"qr.scan_hint":["Dùng nút Quét trong app, không dùng app Camera","请使用应用内扫码，不要用相机应用"],
"qr.label_small":["Nhỏ 70 × 37 mm (24 tem/A4)","小 70 × 37 mm（每张A4 24枚）"],
"qr.label_large":["Lớn 105 × 74 mm (8 tem/A4)","大 105 × 74 mm（每张A4 8枚）"],
"qr.offset":["Chỉnh lệch lề (mm)","边距微调（毫米）"],
"qr.print_hint":["Dùng In của trình duyệt hoặc Lưu PDF; khổ A4, lề 0","请使用浏览器打印或另存为PDF；A4纸，边距0"],
"qr.print_standalone":["Trên app Màn hình chính iPhone không in trực tiếp được: mở bằng Safari hoặc máy tính","iPhone主屏幕应用无法直接打印：请用Safari或电脑打开"],
"misc.interim":["Màn đầy đủ đang được làm trong Đợt 1; tạm thời chỉ xem dữ liệu đã tải","完整页面正在第一阶段开发中，暂时只能查看已下载数据"],
"qr.test_env_warning":["Môi trường THỬ: không in tem thật","测试环境：请勿打印正式标签"],
"qr.entity.EQUIPMENT":["Thiết bị","设备"],
"qr.entity.MATERIAL":["Vật tư","物料"],
"qr.entity.INSPECTION_REQUIREMENT":["Yêu cầu kiểm định","检验要求"],
"qr.entity.CONTRACT":["Hợp đồng thuê ngoài","外包合同"],
"qr.entity.INSPECTION":["Lần kiểm định","检验记录"],
"i18n.lang_vi":["Tiếng Việt","越南语"],
"i18n.lang_zh":["Tiếng Trung","中文"],
"i18n.checked":["Đã kiểm tra bản dịch","已核对译文"],
"doc.too_large":["Tệp quá lớn để mở trong app","文件过大，无法在应用内打开"],
"doc.photo_warning":["Không chụp hợp đồng/chứng nhận vào mục ảnh","请勿将合同或证书作为照片上传"],
"doc.upload_too_large_mobile":["Tệp trên {N} MB: hãy tải lên từ máy tính","超过{N} MB的文件请在电脑上上传"],
"doc.none":["Chưa có tài liệu","暂无文件"],
"doc.uploading":["Đang tải lên…","正在上传…"],
"doc.offline_saved":["Đã lưu để xem ngoại tuyến","已保存以便离线查看"],
"err.network":["Không kết nối được máy chủ","无法连接服务器"],
"err.unknown_result":["Chưa rõ kết quả, đang hỏi lại máy chủ","结果未知，正在向服务器确认"],
"err.client":["Lỗi trên máy","本机错误"],
"err.not_found":["Không tìm thấy","未找到"],
"err.forbidden":["Không có quyền","无权限"],
"login":["Đăng nhập","登录"],
"employee_code":["Mã nhân viên","员工编号"],
"pin6":["PIN 6 số","六位数字密码"],
"forgot_pin":["Quên PIN","忘记PIN"],
"forgot_pin_help":["Liên hệ quản trị để đặt lại PIN","请联系管理员重置密码"],
"same_account":["Dùng cùng tài khoản với iPhone","与iPhone使用同一账户"],
"shared_device":["Máy dùng chung","公用设备"],
"switch_user":["Đăng nhập người khác","切换用户"],
"show_pin":["Hiện PIN","显示PIN"],
"change_pin":["Đổi PIN","修改PIN"],
"temp_pin":["Bạn đang dùng PIN tạm, hãy đặt PIN mới","您正在使用临时PIN，请设置新PIN"],
"current_pin":["PIN hiện tại","当前PIN"],
"new_pin":["PIN mới","新PIN"],
"new_pin_again":["Nhập lại PIN mới","确认新PIN"],
"pin_mismatch":["Hai lần nhập PIN mới không khớp","两次输入的新PIN不一致"],
"no_reuse_pin":["Không dùng lại PIN của app khác","请勿重复使用其他应用的PIN"],
"pin_weak":["PIN quá dễ đoán, hãy chọn PIN khác","PIN过于简单，请换一个"],
"pin_format":["PIN phải gồm đúng 6 chữ số","PIN必须为6位数字"],
"offline_unlock":["Mở khóa ngoại tuyến","离线解锁"],
"open_with_pin":["Mở bằng PIN","用PIN打开"],
"attempts_left":["Còn {N} lần thử","还可尝试 {N} 次"],
"locked":["Tạm khóa do nhập sai PIN nhiều lần, thử lại sau {N} phút","因多次输错PIN已暂时锁定，请 {N} 分钟后重试"],
"revoked":["Phiên đã bị thu hồi hoặc quyền đã thay đổi","会话已撤销或权限已变更"],
"session_warn":["Phiên sắp hết hạn","会话即将到期"],
"relogin":["Đăng nhập lại","重新登录"],
"logout":["Đăng xuất","退出登录"],
"offline":["Ngoại tuyến","离线"],
"local_saved":["Đã lưu trên máy","已保存在本机"],
"queued":["Chờ gửi","待同步"],
"sending":["Đang gửi","同步中"],
"committed":["Đã lưu máy chủ","已同步"],
"conflict":["Xung đột, cần xử lý","冲突，需处理"],
"failed":["Lỗi gửi","同步失败"],
"last_sync":["Lần đồng bộ cuối","上次同步"],
"sync_now":["Đồng bộ ngay","立即同步"],
"need_network":["Cần kết nối mạng","需要网络连接"],
"safari_tab":["Đang chạy trong Safari: nháp có thể bị xóa sau 7 ngày không mở","在Safari中运行：7天未打开草稿可能被清除"],
"dataset_reset":["Dữ liệu đã được đặt lại, cần tải lại","数据已重置，需重新加载"],
"maintenance":["Hệ thống đang bảo trì","系统维护中"],
"network_error":["Không kết nối được máy chủ","无法连接服务器"],
"unknown_result":["Chưa rõ kết quả, đang hỏi lại máy chủ","结果未知，正在向服务器确认"],
"server_url":["Địa chỉ máy chủ (/exec)","服务器地址 (/exec)"],
"server_url_missing":["Chưa có địa chỉ máy chủ","尚未设置服务器地址"],
"server_url_bad":["Link phải có dạng https://script.google.com/macros/s/…/exec","链接格式应为 https://script.google.com/macros/s/…/exec"],
"save":["Lưu","保存"],
"cancel":["Hủy","取消"],
"back":["Quay lại","返回"],
"download":["Tải về","下载"],
"open_save":["Mở / Lưu","打开/保存"],
"set_private":["Đặt riêng tư","设为私有"],
"export_backup":["Xuất dự phòng","导出备份"],
"pending_code":["Chờ cấp mã","待分配编号"],
"machine_translated":["dịch máy","机器翻译"],
"no_translation":["Chưa có bản dịch","暂无译文"],
"sample_data":["Dữ liệu mẫu","示例数据"],
"scan":["Quét QR","扫码"],
"scan_hint":["Dùng nút Quét trong app, không dùng app Camera","请使用应用内扫码，不要用相机应用"],
"open_in_app":["Mở app M&E và dùng nút Quét","请打开M&E应用并使用扫码按钮"],
"continue_here":["Tiếp tục trong Safari","在Safari中继续"],
"manual_code":["Nhập mã","输入编号"],
"qr_foreign":["Mã này không thuộc M&E","此码不属于M&E"],
"qr_unavailable":["Không tìm thấy hoặc không có quyền xem","未找到或无权查看"],
"qr_inactive":["Hồ sơ đã ngừng sử dụng","记录已停用"],
"qr_expired":["Tem đã hết hiệu lực","标签已失效"],
"qr_not_in_restored":["Không có mã này trong dữ liệu hiện tại","当前数据中无此码"],
"doc_too_large":["Tệp quá lớn để mở trong app","文件过大，无法在应用内打开"],
"upload_too_large_mobile":["Tệp trên {N} MB: hãy tải lên từ máy tính","超过{N} MB的文件请在电脑上上传"],
"photo_warning":["Không chụp hợp đồng/chứng nhận vào mục ảnh","请勿将合同或证书作为照片上传"],
"coming_soon":["Sắp có","即将推出"],
"env_test":["THỬ","测试"],
"poc_title":["Kiểm thử PoC","PoC测试"],
"equipment":["Thiết bị","设备"],
"inspections":["Kiểm định","检验"],
"gmail.settings":["Cài đặt gửi","发送设置"],
"gmail.enabled":["Bật gửi Gmail nhắc hạn","启用Gmail到期提醒"],
"gmail.enabled_on":["Đang bật","已启用","green"],
"gmail.enabled_off":["Đang tắt","已关闭","grey"],
"gmail.hour":["Giờ gửi hằng ngày","每日发送时间"],
"gmail.stages":["Mốc gửi cố định: còn 40, 30, 14, 7, 3, 1 ngày, đến hạn; quá hạn nhắc mỗi 7 ngày","固定提醒节点：剩余40、30、14、7、3、1天及到期当天；逾期每7天提醒一次"],
"gmail.quota":["Hạn mức gửi còn lại hôm nay: {N} thư","今日剩余发送额度：{N}封"],
"gmail.test_send":["Gửi thử","发送测试邮件"],
"gmail.test_sent":["Đã gửi thử tới {N} người nhận đã xác nhận","已向{N}位已确认收件人发送测试邮件"],
"gmail.recipients":["Người nhận","收件人"],
"gmail.recipient":["Người nhận","收件人"],
"gmail.email":["Địa chỉ email","邮箱地址"],
"gmail.scope":["Nhận nhắc","接收提醒"],
"gmail.scope.ALL":["Kiểm định và hợp đồng","检验和合同"],
"gmail.scope.INSPECTION":["Chỉ kiểm định","仅检验"],
"gmail.scope.CONTRACT":["Chỉ hợp đồng","仅合同"],
"gmail.user":["Tài khoản gắn kèm (không bắt buộc)","关联账号（可选）"],
"gmail.user_hint":["Gắn tài khoản thì chỉ nhận hồ sơ tài khoản đó được xem; tài khoản bị khóa thì ngừng nhận","关联账号后仅接收该账号可查看的记录；账号停用后停止接收"],
"gmail.confirmed":["Đã xác nhận","已确认","green"],
"gmail.unconfirmed":["Chưa xác nhận — chưa gửi","未确认——不发送","amber"],
"gmail.confirm":["Xác nhận địa chỉ này đúng và được phép nhận thư","确认该地址正确且可以接收邮件"],
"gmail.confirm_hint":["Đổi địa chỉ email thì phải xác nhận lại","更改邮箱地址后需重新确认"],
"gmail.active":["Đang dùng","使用中"],
"gmail.inactive":["Ngừng gửi","停止发送","grey"],
"gmail.add_recipient":["Thêm người nhận","新增收件人"],
"gmail.log":["Nhật ký gửi","发送记录"],
"gmail.log_empty":["Chưa có thư nào","暂无邮件"],
"gmail.stage":["Mốc","节点"],
"gmail.resend_confirm":["Thư này có thể đã tới người nhận. Gửi lại một lần nữa?","该邮件可能已送达。确定再发送一次？"],
"gmail.c3_masked":["Cấp 3 chỉ xem, địa chỉ email được che","三级仅可查看，邮箱地址已隐藏"],
"gmail.error":["Lỗi","错误"],
"gmail.turn_on":["Bật gửi Gmail","开启Gmail发送"],
"gmail.turn_off":["Tắt gửi Gmail","关闭Gmail发送"],
"adm.user.add":["Thêm người dùng","新增用户"],
"adm.user.code":["Mã nhân viên","员工编号"],
"adm.user.email":["Email (không bắt buộc)","邮箱（可选）"],
"adm.user.last_login":["Đăng nhập cuối","最近登录"],
"adm.user.sessions":["Phiên đang mở","在线会话"],
"adm.user.temp_pin_title":["PIN tạm","临时PIN"],
"adm.user.temp_pin_once":["PIN tạm chỉ hiện một lần. Ghi lại và đưa tận tay người dùng; hạn {H} giờ, đăng nhập xong phải đổi PIN","临时PIN只显示一次。请记下并当面交给用户；有效期{H}小时，登录后必须修改PIN"],
"adm.user.temp_pin_until":["Hạn PIN tạm","临时PIN到期"],
"adm.user.self_note":["Tài khoản của bạn: đổi PIN ở trang Tài khoản","这是您的账号：请在账户页修改PIN"],
"adm.user.owner_note":["Chủ hệ thống: chỉ chủ hệ thống thao tác được","系统所有者：仅系统所有者可操作"],
"adm.user.confirm_lock":["Khóa tài khoản này? Mọi phiên sẽ bị thu hồi","锁定该账号？所有会话将被撤销"],
"adm.user.confirm_reset":["Cấp PIN tạm mới? PIN cũ hết dùng, mọi phiên bị thu hồi","发放新的临时PIN？旧PIN失效，所有会话将被撤销"],
"adm.user.confirm_revoke":["Thu hồi mọi phiên của người này? Họ phải đăng nhập lại","撤销该用户的所有会话？该用户需重新登录"],
"adm.user.pin_locked":["Đang khóa do nhập sai PIN","因输错PIN被锁定","amber"],
"adm.user.role_note":["Đổi cấp hoặc vai trò làm mọi phiên của người này hết hiệu lực","修改级别或岗位后，该用户所有会话失效"],
"adm.user.total":["{N} tài khoản","共{N}个账号"],
"btn.reset_pin":["Cấp PIN tạm","发放临时PIN"],
"btn.lock":["Khóa","锁定"],
"btn.unlock":["Mở khóa","解锁"],
"btn.set_role":["Đổi cấp/vai trò","修改级别/岗位"],
"btn.revoke_sessions":["Thu hồi phiên","撤销会话"],
"btn.copied":["Đã chép","已复制"],
"btn.copy":["Chép","复制"],
"perm_flag.V":["Xem","查看"],
"perm_flag.C":["Tạo","新建"],
"perm_flag.E":["Sửa","编辑"],
"perm_flag.A":["Duyệt","审批"],
"perm_flag.I":["Nhập Excel","导入"],
"perm_flag.X":["Xuất","导出"],
"perm_flag.$":["Xem giá","查看价格"],
"perm_flag.R":["Xóa sạch","清空"],
"perm_module.catalog":["Danh mục chung","基础数据"],
"perm_module.users":["Người dùng","用户"],
"perm_module.notifications":["Nhắc hạn, Gmail","提醒与邮件"],
"perm_module.audit":["Nhật ký","日志"],
"perm_module.backup":["Sao lưu","备份"],
"perm_module.system":["Hệ thống","系统"],
"adm.perm.review_note":["Duyệt bảng quyền này trước khi nhập dữ liệu thật","录入真实数据前请先审核本权限表"],
"adm.perm.locked":["Ô khóa: không sửa trong app","锁定项：不能在应用中修改"],
"adm.perm.ceiling":["Vượt trần quyền của cấp này","超出该级别的权限上限"],
"adm.perm.unsaved":["Đã đổi {N} ô, chưa lưu","已修改{N}项，未保存"],
"adm.perm.saved":["Đã lưu, có hiệu lực ngay","已保存，立即生效"],
"adm.perm.subrole_map":["Vai trò cấp 2 → module chính (cố định trong mã, chỉ đọc)","二级岗位→主模块（代码固定，只读）"],
"adm.perm.legend":["V Xem · C Tạo · E Sửa · A Duyệt · I Nhập Excel · X Xuất · $ Xem giá · R Xóa sạch","V查看 · C新建 · E编辑 · A审批 · I导入 · X导出 · $查看价格 · R清空"],
"adm.cat.locations":["Khu vực","区域"],
"adm.cat.vendors":["Nhà cung cấp","供应商"],
"adm.cat.lookups":["Danh mục tra cứu","查找值"],
"adm.cat.glossary":["Thuật ngữ","术语表"],
"location_type.AREA":["Khu vực","区域"],
"location_type.BUILDING":["Tòa nhà","楼栋"],
"location_type.WORKSHOP":["Xưởng","车间"],
"location_type.ROOM":["Phòng","房间"],
"location_type.STATION":["Trạm","站"],
"location_type.OTHER":["Khác","其他"],
"field.location_code":["Mã khu vực","区域编号"],
"field.parent_location":["Khu vực cha","上级区域"],
"field.location_type":["Loại khu vực","区域类型"],
"field.vendor_code":["Mã nhà cung cấp","供应商编号"],
"field.vendor_name":["Tên nhà cung cấp","供应商名称"],
"field.contact_name":["Người liên hệ","联系人"],
"field.phone":["Điện thoại","电话"],
"field.email":["Email","邮箱"],
"field.address":["Địa chỉ","地址"],
"field.services":["Dịch vụ","服务内容"],
"field.lookup_group":["Nhóm","分组"],
"field.lookup_code":["Mã","编码"],
"field.lookup_code_hint":["Mẫu thông số: chữ thường, số, gạch dưới (vd belt_speed). Mã không đổi sau khi tạo","参数模板：小写字母、数字、下划线（如 belt_speed）。创建后编码不可修改"],
"field.term_vi":["Thuật ngữ tiếng Việt","越南语术语"],
"field.term_zh":["Thuật ngữ tiếng Trung","中文术语"],
"field.in_use":["Đang dùng","使用中"],
"catalog.active":["Đang dùng","使用中","green"],
"catalog.inactive":["Ngừng dùng","停用","grey"],
"glossary.approved":["Đã duyệt","已审核","green"],
"glossary.unapproved":["Chưa duyệt — chưa dùng khi dịch","未审核——翻译时不使用","amber"],
"glossary.approve":["Duyệt để dùng khi dịch máy","审核后用于机器翻译"],
"glossary.help":["Chỉ thuật ngữ đã duyệt mới được dùng khi dịch máy; đổi thuật ngữ phải duyệt lại","只有已审核的术语才会用于机器翻译；修改术语后需重新审核"],
"adm.backup.note":["Tự động hằng tuần ({D}, {H}:00), giữ {N} bản đã kiểm chứng. Khôi phục làm thủ công theo hướng dẫn","每周自动备份（{D} {H}:00），保留{N}份已校验备份。恢复需按指南手动操作"],
"adm.backup.queued":["Đang chờ sao lưu, màn tự cập nhật…","等待备份中，页面自动刷新…"],
"adm.backup.rows":["Số dòng","行数"],
"adm.backup.docs":["Tài liệu","文件"],
"adm.backup.time":["Thời điểm","时间"],
"adm.backup.retry":["Chạy lại sau ghi đồng thời","因同时写入而重跑"],
"adm.backup.last":["Lần sao lưu gần nhất","最近一次备份"],
"adm.backup.restored":["Đã khôi phục lúc {T} từ bản {R}","已于{T}从备份{R}恢复"],
"adm.backup.none":["Chưa có bản sao lưu","暂无备份"],
"adm.audit.tab_ops":["Thao tác","操作"],
"adm.audit.tab_auth":["Đăng nhập","登录记录"],
"adm.audit.before":["Trước","修改前"],
"adm.audit.after":["Sau","修改后"],
"adm.audit.user":["Người làm","操作人"],
"adm.audit.time":["Thời gian","时间"],
"adm.audit.action":["Thao tác","操作"],
"adm.audit.entity":["Hồ sơ","记录"],
"adm.audit.from":["Từ ngày","从"],
"adm.audit.to":["Đến ngày","至"],
"adm.audit.more":["Còn nữa — thu hẹp bộ lọc để xem thêm","还有更多——请缩小筛选范围"],
"adm.audit.module_all":["Mọi module","全部模块"],
"adm.audit.sessions":["Phiên đang hiệu lực","有效会话"],
"adm.audit.attempts":["Lần đăng nhập gần đây","最近登录尝试"],
"auth_outcome.SUCCESS":["Thành công","成功","green"],
"auth_outcome.FAILED":["Sai PIN","PIN错误","red"],
"auth_outcome.LOCKED":["Đang khóa","已锁定","red"],
"auth_outcome.PAUSED":["Tạm dừng đăng nhập","暂停登录","amber"],
"auth_outcome.DISABLED":["Tài khoản ngừng dùng","账号已停用","grey"],
"auth_outcome.TEMP_PIN_EXPIRED":["PIN tạm hết hạn","临时PIN已过期","amber"],
"auth_outcome.MUST_CHANGE_PIN":["Đăng nhập bằng PIN tạm","使用临时PIN登录","amber"],
"auth_kind.LOGIN":["Đăng nhập","登录"],
"auth_kind.REAUTH":["Nhập lại PIN","重新输入PIN"],
"auth_kind.CHANGE_PIN":["Đổi PIN","修改PIN"],
"adm.status.ok":["Đạt","正常","green"],
"adm.status.warn":["Cảnh báo","警告","amber"],
"adm.status.checked_at":["Kiểm lúc {T}","检查于{T}"],
"adm.status.settings":["Cấu hình","系统设置"],
"adm.status.readonly":["Chỉ đọc","只读","grey"],
"adm.status.default":["Mặc định","默认"],
"adm.status.maint_note":["Bật/tắt bảo trì chạy từ trình soạn Apps Script (adminMaintenanceOn/Off)","维护模式在Apps Script编辑器中开关（adminMaintenanceOn/Off）"],
"adm.status.base_mismatch":["Khác địa chỉ app đang dùng ({U})","与当前应用地址不同（{U}）"],
"adm.status.edit_setting":["Sửa cấu hình","修改设置"],
"health.schema_version":["Phiên bản schema","架构版本"],
"health.server_version":["Phiên bản máy chủ","服务器版本"],
"health.dataset_epoch":["Thế hệ dữ liệu","数据批次"],
"health.env":["Môi trường","环境"],
"health.maintenance":["Bảo trì","维护模式"],
"health.triggers":["Trigger đã cài","已安装触发器"],
"health.trigger_minutes_24h":["Phút chạy trigger trong 24 giờ","24小时触发器运行分钟数"],
"health.last_backup":["Sao lưu gần nhất","最近备份"],
"health.mt_paused_until":["Tạm dừng dịch máy đến","机器翻译暂停至"],
"health.login_paused_until":["Tạm dừng đăng nhập đến","登录暂停至"],
"health.mail_quota":["Hạn mức Gmail còn lại hôm nay","今日Gmail剩余额度"],
"health.last_mail_sent":["Thư nhắc hạn gửi gần nhất","最近发送的提醒邮件"],
"health.app_base_url":["Địa chỉ app trong email","邮件中的应用地址"],
"health.permissions_ceiling":["Ô quyền vượt trần hoặc thiếu","超出上限或缺失的权限项"],
"health.documents_broken":["Tài liệu không mở được","无法打开的文件"],
"health.spreadsheet_cells":["Số ô bảng tính (giới hạn 5 triệu)","表格单元格数（上限500万）"],
"adm.perm.module":["Module","模块"],
"excel.title":["Nhập/xuất Excel","Excel导入导出"],
"excel.tpl.glossary":["Thuật ngữ","术语表"],
"excel.tpl.locations":["Khu vực","区域"],
"excel.tpl.lookups":["Danh mục tra cứu","查找值"],
"excel.tpl.vendors":["Nhà cung cấp","供应商"],
"excel.tpl.materials":["Vật tư","物料"],
"excel.tpl.equipment":["Thiết bị và thông số","设备及参数"],
"excel.tpl.equipment_parts":["Linh kiện theo máy","设备配件"],
"excel.tpl.inspection_types":["Loại kiểm định","检验类型"],
"excel.tpl.inspection_requirements":["Yêu cầu kiểm định","检验要求"],
"excel.tpl.inspections":["Chứng nhận kiểm định","检验证书"],
"excel.tpl.contracts":["Hợp đồng và thiết bị","合同及设备"],
"excel.tpl.alerts":["Nhắc hạn","到期提醒"],
"excel.download_template":["Tải mẫu","下载模板"],
"excel.choose_file":["Chọn tệp .xlsx để nhập","选择要导入的.xlsx文件"],
"excel.reading":["Đang đọc tệp…","正在读取文件…"],
"excel.sending":["Đang gửi kiểm tra {N}/{T} dòng…","正在提交校验 {N}/{T} 行…"],
"excel.committing":["Đang ghi {N}/{T} dòng…","正在写入 {N}/{T} 行…"],
"excel.summary":["Kết quả kiểm tra","校验结果"],
"excel.add":["Thêm mới","新增"],
"excel.update":["Cập nhật","更新"],
"excel.errors":["Lỗi","错误"],
"excel.mt_fields":["{N} trường sẽ được dịch máy sau khi nhập","导入后将机器翻译{N}个字段"],
"excel.sensitive":["Lô nhạy cảm: người khác người nhập duyệt và ghi, có PIN; ghi là duyệt","敏感批次：须由导入人以外的人员审核写入（需PIN），写入即审核"],
"excel.btn_commit":["Nhập dữ liệu","导入数据"],
"excel.btn_submit":["Gửi duyệt","提交审核"],
"excel.btn_cancel":["Hủy lô","取消批次"],
"excel.btn_errors":["Tải danh sách lỗi","下载错误清单"],
"excel.btn_open":["Mở lô","打开批次"],
"excel.changes":["Trước – sau","修改前后"],
"excel.sheet":["Sheet","工作表"],
"excel.row":["Dòng","行"],
"excel.field":["Cột","列"],
"excel.batches":["Lô gần đây","最近批次"],
"excel.committed":["Đã ghi {N} dòng","已写入{N}行"],
"excel.failed_rows":["{N} dòng lỗi khi ghi","写入失败{N}行"],
"excel.blocked":["Có lỗi: sửa tệp rồi chọn lại, nút Nhập dữ liệu bị khóa","有错误：请修改文件后重新选择，导入按钮已锁定"],
"excel.wait_approval":["Đã gửi duyệt, chờ Trưởng bộ phận/Quản trị ghi","已提交审核，等待主管/管理员写入"],
"excel.due":["Lọc hạn","期限筛选"],
"excel.due.ALL":["Tất cả","全部"],
"excel.due.DUE40":["Trong 40 ngày và quá hạn","40天内及已逾期"],
"excel.due.OVERDUE":["Quá hạn","已逾期"],
"excel.guide.title":["Hướng dẫn","使用说明"],
"excel.guide.1":["Dòng 1 là khóa cột, không sửa; dòng 2 là nhãn; nhập dữ liệu từ dòng 3","第1行为列键，请勿修改；第2行为标签；从第3行开始填写"],
"excel.guide.2":["Thêm mới: để trống cột ID. Sửa: giữ ID và record_version từ file xuất","新增：ID列留空。修改：保留导出文件中的ID和record_version"],
"excel.guide.3":["Ngày ghi dd/mm/yyyy; mã là chữ (giữ số 0 đầu); không dùng công thức","日期格式dd/mm/yyyy；编号为文本（保留前导0）；不要使用公式"],
"excel.guide.4":["Xóa một dòng trong file không xóa hồ sơ","在文件中删除行不会删除记录"],
"excel.guide.5":["Chỉ cần nhập một thứ tiếng; máy chủ dịch sau khi nhập","只需填写一种语言；导入后服务器自动翻译"],
"excel.guide.6":["Thứ tự nhập: thuật ngữ → khu vực → danh mục tra cứu → nhà cung cấp → vật tư → thiết bị → linh kiện → loại kiểm định → yêu cầu kiểm định → chứng nhận → hợp đồng","导入顺序：术语→区域→查找值→供应商→物料→设备→配件→检验类型→检验要求→证书→合同"],
"excel.lists":["Danh mục mã","编码清单"],
"excel.filters":["Điều kiện lọc","筛选条件"],
"excel.generated_at":["Lúc tạo","生成时间"],
"excel.generated_by":["Người tạo","生成人"],
"excel.scope":["Phạm vi","范围"],
"excel.required":["Bắt buộc","必填"],
"excel.options":["Giá trị cho phép","允许值"],
"excel.no_rows":["Tệp không có dòng dữ liệu (từ dòng 3)","文件没有数据行（从第3行起）"],
"excel.bad_file":["Không đọc được tệp hoặc thiếu sheet {S}","无法读取文件或缺少工作表{S}"],
"excel.exported":["Đã tạo tệp Excel","已生成Excel文件"],
"i18n.suggest":["Gợi ý dịch","翻译建议"],
"i18n.suggest_need_one":["Nhập một bên rồi bấm Gợi ý dịch","先填写一种语言再点翻译建议"],
"i18n.check_required":["Tick \"Đã kiểm tra bản dịch\" trước khi lưu","保存前请勾选\"已核对译文\""],
"i18n.retranslate":["Dịch lại","重新翻译"],
"i18n.retranslated":["Đã dịch lại","已重新翻译"],
"i18n.still_pending":["Dịch chưa được, thử lại sau","暂时无法翻译，请稍后再试"]};
